version: '3.5'
services:
  api:
    container_name: cfa-strapi
    restart: 'always'
    logging:
      options:
        max-size: '10m'
    build:
      context: .
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./public/uploads:/app/public/uploads
    expose:
      - '${PORT}'
    env_file:
      - .env

  # mysql:
  #   image: mysql:5.7
  #   hostname: mysql
  #   container_name: cfa-mysql
  #   restart: always
  #   ports:
  #     - '${DB_PORT}:3306'
  #   volumes:
  #     - ./database/mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #   env_file:
  #     - .env
